import "./globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Mobilenavbar from "@/components/mobilenavbar";
import Navbar from "@/components/navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<UserProvider>
			<html lang="en">
				<Head>
					<style>
						@import
						url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,300&display=swap');
					</style>
				</Head>
				<body className={inter.className}>
					<header className="mb-16 md:mb-24">
						<Mobilenavbar />
						<Navbar />
					</header>
					{children}
				</body>
			</html>
		</UserProvider>
	);
}
